const rule = (pattern, permission) => ({ pattern, permission });

export const ROUTE_PERMISSION_RULES = [
    rule(/^\/platform$/, 'platform.dashboard.view'),
    rule(/^\/platform\/tenants\/new$/, 'platform.tenants.create'),
    rule(/^\/platform\/tenants(?:\/[^/]+)?$/, 'platform.tenants.view'),
    rule(/^\/platform\/plans$/, 'platform.plans.view'),
    rule(/^\/platform\/audit$/, 'platform.audit.view'),
    rule(/^\/platform\/monitoring$/, 'platform.monitoring.view'),
    rule(/^\/platform\/settings$/, 'platform.settings.view'),

    rule(/^\/tenant$/, 'tenant.dashboard.view'),
    rule(/^\/tenant\/branding$/, 'tenant.branding.view'),
    rule(/^\/tenant\/branches$/, 'tenant.branches.view'),
    rule(/^\/tenant\/users$/, 'tenant.users.view'),
    rule(/^\/tenant\/academic-years$/, 'tenant.academicYears.view'),
    rule(/^\/tenant\/reports$/, 'tenant.reports.view'),
    rule(/^\/tenant\/enrollments\/promote$/, 'tenant.promotions.run'),
    rule(/^\/tenant\/enrollments\/transfer$/, 'tenant.transfers.run'),
    rule(/^\/tenant\/audit-logs$/, 'tenant.audit.view'),

    rule(/^\/finance$/, 'finance.dashboard.view'),
    rule(/^\/finance\/policies$/, 'finance.policies.view'),
    rule(/^\/finance\/fee-structures$/, 'finance.feeStructures.view'),
    rule(/^\/finance\/invoices\/generate$/, 'finance.invoices.generate'),
    rule(/^\/finance\/invoices\/[^/]+$/, 'finance.invoices.detail'),
    rule(/^\/finance\/invoices$/, 'finance.invoices.view'),
    rule(/^\/finance\/payments$/, 'finance.payments.view'),
    rule(/^\/finance\/reports$/, 'finance.reports.view'),
    rule(/^\/finance\/outstanding$/, 'finance.outstanding.view'),
    rule(/^\/finance\/receipt-branding$/, 'finance.receiptBranding.view'),

    rule(/^\/branch$/, 'branch.dashboard.view'),
    rule(/^\/branch\/profile$/, 'branch.profile.view'),
    rule(/^\/branch\/classes$/, 'branch.classes.view'),
    rule(/^\/branch\/staff$/, 'branch.staff.view'),
    rule(/^\/branch\/students$/, 'branch.students.view'),
    rule(/^\/branch\/promotions$/, 'branch.promotions.run'),
    rule(/^\/branch\/exams$/, 'branch.exams.view'),
    rule(/^\/branch\/results(?:\/student)?$/, 'branch.results.view'),
    rule(/^\/branch\/assignments$/, 'branch.assignments.view'),
    rule(/^\/branch\/timetable(?:\/class\/[^/]+)?$/, 'branch.timetable.view'),
    rule(/^\/branch\/reports$/, 'branch.reports.view'),
    rule(/^\/branch\/hr\/leaves$/, 'hr.leaves.review'),
    rule(/^\/branch\/hr\/payroll$/, 'payroll.view'),

    rule(/^\/registrar$/, 'registrar.dashboard.view'),
    rule(/^\/registrar\/admissions$/, 'students.create'),
    rule(/^\/registrar\/students\/[^/]+$/, 'students.detail'),
    rule(/^\/registrar\/students$/, 'students.view'),
    rule(/^\/registrar\/enrollments\/new$/, 'enrollments.create'),
    rule(/^\/registrar\/transfers$/, 'transfers.branch.create'),

    rule(/^\/cashier$/, 'cashier.dashboard.view'),
    rule(/^\/cashier\/invoices\/[^/]+$/, 'cashier.invoices.detail'),
    rule(/^\/cashier\/invoices$/, 'cashier.invoices.search'),
    rule(/^\/cashier\/payments\/new$/, 'cashier.payments.create'),
    rule(/^\/cashier\/payments$/, 'cashier.payments.view'),
    rule(/^\/cashier\/receipts\/[^/]+$/, 'cashier.receipts.view'),

    rule(/^\/teacher$/, 'teacher.dashboard.view'),
    rule(/^\/teacher\/templates$/, 'teacher.examTemplates.view'),
    rule(/^\/teacher\/categories$/, 'teacher.examCategories.view'),
    rule(/^\/teacher\/exams(?:\/[^/]+)?$/, 'teacher.exams.view'),
    rule(/^\/teacher\/results-entry(?:\/[^/]+)?$/, 'teacher.results.enter'),
    rule(/^\/teacher\/results$/, 'teacher.results.view'),
    rule(/^\/teacher\/reports$/, 'teacher.results.view'),
    rule(/^\/teacher\/exports$/, 'teacher.results.export'),
    rule(/^\/teacher\/grading-policy$/, 'teacher.gradingPolicy.view'),
    rule(/^\/teacher\/schedule$/, 'teacher.schedule.view'),
    rule(/^\/teacher\/attendance\/[^/]+$/, 'teacher.attendance.submit'),
    rule(/^\/teacher\/attendance$/, 'teacher.attendance.view'),
    rule(/^\/teacher\/leaves$/, 'teacher.leaves.create'),

    rule(/^\/student$/, 'student.dashboard.view'),
    rule(/^\/student\/results$/, 'student.results.view'),
    rule(/^\/student\/rank$/, 'student.rank.view'),
    rule(/^\/student\/schedule$/, 'student.schedule.view'),
    rule(/^\/student\/attendance$/, 'student.attendance.view'),
    rule(/^\/student\/profile$/, 'student.profile.view'),
    rule(/^\/student\/change-password$/, 'student.password.change'),

    rule(/^\/parent\/profile$/, 'parent.profile.view'),
    rule(/^\/parent$/, 'parent.dashboard.view'),
    rule(/^\/parent\/grades$/, 'parent.grades.view'),
    rule(/^\/parent\/attendance$/, 'parent.attendance.view'),
    rule(/^\/parent\/invoices$/, 'parent.invoices.view')
];

export const getRequiredPermissionForPath = (pathname = '') => (
    ROUTE_PERMISSION_RULES.find(({ pattern }) => pattern.test(pathname))?.permission || null
);
